name: CI

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: actions-rs/toolchain@v1.0.7
    - run: cargo test --no-default-features
    - run: cargo test
    - run: cargo test --all-features

  check:
    name: Check on Rust ${{matrix.rust}}${{format(' ({0})', matrix.target || matrix.os)}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os: [ubuntu]
        rust: ['1.56', stable, beta, nightly]
    env:
      target: ${{matrix.target && format('--target={0}', matrix.target)}}
      workspace: ${{matrix.no-workspace || '--workspace'}}
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{matrix.rust}}
        profile: minimal
        target: ${{matrix.target}}
    - run: cargo +${{matrix.rust}} check ${{env.target}} ${{env.workspace}} --no-default-features
    - run: cargo +${{matrix.rust}} check ${{env.target}} ${{env.workspace}}
    - run: cargo +${{matrix.rust}} check ${{env.target}} ${{env.workspace}} --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        profile: minimal
        components: clippy
    - run: cargo clippy --no-default-features
    - run: cargo clippy
    - run: cargo clippy --all-features

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
    - run: cargo fmt --all -- --check

  # We need some "accummulation" job here because bors fails (timeouts) to
  # listen on matrix builds.
  # Hence, we have some kind of dummy here that bors can listen on
  ci-success:
    name: CI
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs:
      - check
      - test
      - clippy
      - fmt
    steps:
      - name: CI succeeded
        run: exit 0
