name: Deny Warnings

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  deny-warnings:
    name: Deny Warnings
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        profile: minimal
        components: clippy
    - run: cargo clippy --all-targets --no-default-features -- -D warnings
    - run: cargo clippy --all-targets -- -D warnings
    - run: cargo clippy --all-targets --all-features -- -D warnings
